<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            $table->id();

            // Report type
            $table->enum('type', ['sales', 'orders', 'unclaimed', 'analytics', 'custom']);

            // Report name
            $table->string('name');

            // Generated by
            $table->foreignId('generated_by')->constrained('users')->onDelete('cascade');

            // Branch (NULL = all branches)
            $table->foreignId('branch_id')->nullable()->constrained()->onDelete('cascade');

            // Date range
            $table->date('start_date');
            $table->date('end_date');

            // Report data (JSON)
            $table->json('data');

            // File path (if exported)
            $table->string('file_path')->nullable();

            // Status
            $table->enum('status', ['pending', 'completed', 'failed'])->default('pending');

            $table->timestamps();

            // Indexes
            $table->index('type');
            $table->index('generated_by');
            $table->index('branch_id');
            $table->index(['start_date', 'end_date']);
            $table->index('created_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
